---@class spell_instance_script
---@field public last_target_id any
---@field public do_cast_time number
---@field public cast_start_time number
---@field public attack_delay number
---@field public attack_cast_delay number
---@field public time number
---@field public is_winding_up boolean
---@field public is_auto_attack boolean
---@field public spell_has_been_casted boolean
---@field public is_auto_attacking boolean
---@field public is_charging boolean
---@field public is_channeling boolean
---@field public is_stopped boolean
---@field public start_position vector
---@field public end_position vector
---@field public spell_data spell_data_script
---@field public spellslot any
---@field public level number
local spell_instance_script = {}

