---@class minion_table
---@field public all game_object_script[]
---@field public enemy game_object_script[]
---@field public ally game_object_script[]
---@field public neutral game_object_script[]
---@field public barrel game_object_script[]
---@field public other game_object_script[]
